name: guess_the_object
description: "Real-time multiplayer guessing game. Two players, one category, different objects. Ask questions, guess the object, win the match."
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_database: ^12.4.4
  google_sign_in: ^7.2.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^17.3.0

  # Code Generation Support
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utilities
  uuid: ^4.5.3
  equatable: ^2.1.0

  # Audio & Haptics
  audioplayers: ^6.7.1
  vibration: ^3.2.0
  flutter_dotenv: ^6.0.1

  # In-App Updates
  package_info_plus: ^8.0.0
  http: ^1.2.0
  path_provider: ^2.1.0
  open_filex: ^4.7.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generators
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - .env
